version: "3"
 
services:
 
  master:
    image: johnydickens/openmpi:v2
    entrypoint: /bin/bash
    container_name: master
    ports:
      - 5222:22
    networks:
      - mpi
    stdin_open: true
    tty: true
    
  nodo1:
    image: johnydickens/openmpi:v2
    entrypoint: /bin/bash
    container_name: nodo1
    ports:
      - 5323:22
    networks:
      - mpi
    stdin_open: true
    tty: true

  nodo2:
    image: johnydickens/openmpi:v2
    entrypoint: /bin/bash
    container_name: nodo2
    ports:
      - 5424:22
    networks:
      - mpi
    stdin_open: true
    tty: true

      
networks:
  mpi:
    external: true